### ISSUE TITLE
outdated plugin

### ISSUE THREAD

**Issue by Mac10Monarch** [Kirrana/xivlauncher_physics_plugin#12]
Patch 7.0 for Dalamud are out. Just wanted to let you guys know if you haven't seen it already

**Comment by Kirrana** [comment]
Signatures broke, dunno when I'll get around to looking at it as I haven't worked on this for more than a year and am both very out of the loop and very busy atm.

**Comment by Kirrana** [comment]
I think I might have gotten it to work way faster than it took to install all the programs used to figure stuff out actually, assuming I don't encounter anything broken today I'll push it after work tomorrow I guess (so like 24h from now)

**Comment by ChrisZehr** [comment]
Fingers crossed!  Thanks!

**Comment by Mac10Monarch** [comment]
> Fingers crossed! Thanks!

Thank you! It's small, but I like the extra physics :)

**Comment by ChrisZehr** [comment]
> > Fingers crossed! Thanks!
> 
> Thank you! It's small, but I like the extra physics :)

I just hate being _punished_ for having a high framerate

**Comment by TheLizardizzle** [comment]
Absolutely one of the best plugins and I'm glad to hear that it may be working!

**Comment by chennin** [comment]
Hello! The 7.0 patch notes contain this line:

> Movement from wind will appear more consistent at high frame rates.

Has anyone tested to see what that actually means and how it overlaps with what this plugin does? And what about for jumping puzzles being easier at low FPS?

**Comment by ChrisZehr** [comment]
> And what about for jumping puzzles being easier at low FPS?

If anything I've only had an easier time at higher fps

**Comment by Mac10Monarch** [comment]
> > And what about for jumping puzzles being easier at low FPS?
> 
> If anything I've only had an easier time at higher fps

not sure what puzzles you're referring to exactly (I think I'm going to be done with (non post)shadowbringers here in a bit).

**Comment by ChrisZehr** [comment]
Seems to be working fine for me, thanks Kirrana!

**Comment by kaedede** [comment]
> I think I might have gotten it to work way faster than it took to install all the programs used to figure stuff out actually, assuming I don't encounter anything broken today I'll push it after work tomorrow I guess (so like 24h from now)

You are the GOAT! Thank youuuu
