### ISSUE TITLE
/physics command revert

### ISSUE THREAD

**Issue by Dajova** [Kirrana/xivlauncher_physics_plugin#6]
I noticed that you made it so `/physics` opens up a config window instead of toggling it and added `on` and `off` for toggling purposes now. I much prefer the way it was previously, so i only needed a single command to toggle between them instead of having 2 commands to turn it on and off.

Maybe split them so you could open config with `/physics config` or changing on/off to `/physics toggle`.

**Comment by Kirrana** [comment]
Fix adding `/physics t` that toggles pushed.
